In [44]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score,r2_score
from sklearn.preprocessing import StandardScaler,MinMaxScaler


In [45]:
df = pd.read_csv('Admission_Predict_Ver1.1.csv')
df.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

In [46]:
df.columns

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')

In [47]:
X = df.drop(['Serial No.','Chance of Admit '],1)
Y = df['Chance of Admit ']

In [48]:
X_train,X_test,y_train,y_test = train_test_split(X,Y, test_size = 0.2, random_state = 100)
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(400, 7) (100, 7) (400,) (100,)


In [49]:
# sc = StandardScaler()
sc = MinMaxScaler()
scaled_X_train = sc.fit_transform(X_train)
scaled_X_test = sc.transform(X_test)

scaled_X_train[0:5]

array([[0.1       , 0.25      , 0.25      , 0.375     , 0.5       ,
        0.2724359 , 0.        ],
       [0.42      , 0.32142857, 0.5       , 0.25      , 0.375     ,
        0.26923077, 1.        ],
       [0.84      , 0.92857143, 1.        , 1.        , 1.        ,
        0.85576923, 1.        ],
       [0.3       , 0.42857143, 0.25      , 0.375     , 0.125     ,
        0.31730769, 0.        ],
       [0.6       , 0.39285714, 0.5       , 0.5       , 0.5       ,
        0.28846154, 0.        ]])

In [50]:
model = Sequential([
    Dense(7,'relu',input_dim = 7),
    Dense(7,'relu'),
    Dense(1,'linear')
])

In [51]:
model.compile(optimizer='adam',loss='mse',metrics = ['mse'])

In [52]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_13 (Dense)             (None, 7)                 56        
_________________________________________________________________
dense_14 (Dense)             (None, 7)                 56        
_________________________________________________________________
dense_15 (Dense)             (None, 1)                 8         
Total params: 120
Trainable params: 120
Non-trainable params: 0
_________________________________________________________________


In [53]:
hist = model.fit(scaled_X_train,y_train, validation_split = 0.2, epochs = 100)

Epoch 1/100
10/10 [==============================] - 0s 13ms/step - loss: 0.6502 - mse: 0.6502 - val_loss: 0.5538 - val_mse: 0.5538
Epoch 2/100
10/10 [==============================] - 0s 5ms/step - loss: 0.5601 - mse: 0.5601 - val_loss: 0.4948 - val_mse: 0.4948
Epoch 3/100
10/10 [==============================] - 0s 3ms/step - loss: 0.5149 - mse: 0.5149 - val_loss: 0.4590 - val_mse: 0.4590
Epoch 4/100
10/10 [==============================] - 0s 4ms/step - loss: 0.4844 - mse: 0.4844 - val_loss: 0.4313 - val_mse: 0.4313
Epoch 5/100
10/10 [==============================] - 0s 4ms/step - loss: 0.4570 - mse: 0.4570 - val_loss: 0.4038 - val_mse: 0.4038
Epoch 6/100
10/10 [==============================] - 0s 3ms/step - loss: 0.4265 - mse: 0.4265 - val_loss: 0.3662 - val_mse: 0.3662
Epoch 7/100
10/10 [==============================] - 0s 3ms/step - loss: 0.3837 - mse: 0.3837 - val_loss: 0.3137 - val_mse: 0.3137
Epoch 8/100
10/10 [==============================] - 0s 4ms/step - loss: 0.3269 - 

In [54]:
y_prob = model.predict(scaled_X_test)
np.concatenate((y_prob.reshape(len(y_prob),1),y_test.values.reshape(len(y_test),1)),1)

array([[0.86915129, 0.78      ],
       [0.51337308, 0.54      ],
       [0.63686478, 0.64      ],
       [0.46111599, 0.47      ],
       [0.68291259, 0.7       ],
       [0.86264122, 0.88      ],
       [0.60784799, 0.57      ],
       [0.63027334, 0.72      ],
       [0.82326651, 0.84      ],
       [0.66297948, 0.64      ],
       [0.70091701, 0.79      ],
       [0.59577364, 0.56      ],
       [0.87384939, 0.92      ],
       [0.68630743, 0.79      ],
       [0.67143095, 0.73      ],
       [0.52092105, 0.52      ],
       [0.62850982, 0.62      ],
       [0.76217151, 0.81      ],
       [0.55081052, 0.57      ],
       [0.71820366, 0.65      ],
       [0.87865824, 0.93      ],
       [0.63474745, 0.65      ],
       [0.86540037, 0.86      ],
       [0.82576668, 0.87      ],
       [0.95495421, 0.97      ],
       [0.63739878, 0.65      ],
       [0.69395095, 0.57      ],
       [0.93776786, 0.95      ],
       [0.87989259, 0.91      ],
       [0.72600561, 0.74      ],
       [0.

In [55]:
r2_score(y_prob,y_test)

0.7737343195313745

In [73]:
x_t = np.array(sc.transform([[314,110,2,4.5,4.5,7.78,0]]))
model.predict(x_t)

array([[0.61099374]], dtype=float32)